services:
  frontend:
    container_name: Flinky Frontend
    depends_on:
      - flinky_server
    build:
      context: ./client
      dockerfile: Dockerfile

  flinky_server:
    container_name: Flinky Server
    depends_on:
      - flinky_db
      - flinky_redis
    build:
      context: ./server
      dockerfile: Dockerfile

  flinky_db:
    container_name: Flinky Postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flinky_db
    ports:
      - "5432:5432"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - flinky_postgres:/var/lib/postgresql/data

  flinky_redis:
    container_name: Flinky Redis Cache
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  flinky_postgres: